### ISSUE TITLE
Python HybirdStream Test Exception

### ISSUE THREAD

**Issue by ashione** [ray-project/mobius#44]
When I was running python test
```bash
python -m pytest python/raystreaming/tests/test_hybrid_stream.py --capture=no
```
outputs are 
```

(raylet) java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
(raylet)        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
(raylet)        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
(raylet)        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
(raylet)        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
(raylet)        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
(raylet)        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
(raylet)        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) 
(raylet)        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
(raylet) Caused by: java.lang.ExceptionInInitializerError
(raylet)        at java.lang.Class.forName0(Native Method)
(raylet)        at java.lang.Class.forName(Class.java:348)
(raylet)        at io.ray.runtime.util.MethodUtils.getReturnTypeFromSignature(MethodUtils.java:51)
(raylet)        at io.ray.runtime.util.ConcurrencyGroupUtils.extractConcurrencyGroupsByAnnotations(ConcurrencyGroupUtils.java:25)
(raylet)        at io.ray.runtime.AbstractRayRuntime.extractConcurrencyGroups(AbstractRayRuntime.java:288)
(raylet)        at io.ray.api.call.ActorCreator.<init>(ActorCreator.java:25)
(raylet)        at io.ray.api.RayCall.actor(RayCall.java:1314)
(raylet)        at io.ray.streaming.runtime.master.scheduler.controller.WorkerLifecycleController.createWorker(WorkerLifecycleController.java:54)
(raylet)        at io.ray.streaming.runtime.master.scheduler.controller.WorkerLifecycleController.lambda$asyncBatchExecute$3(WorkerLifecycleController.java:200)
(raylet)        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
(raylet)        ... 5 more
(raylet) Caused by: java.lang.NullPointerException: {} doesn't exist. [native/linux/libstreaming_java.so]
(raylet)        at io.ray.shaded.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1007)
(raylet)        at io.ray.runtime.util.BinaryFileUtil.getNativeFile(BinaryFileUtil.java:64)
(raylet)        at io.ray.runtime.util.JniUtils.loadLibrary(JniUtils.java:67)
(raylet)        at io.ray.runtime.util.JniUtils.loadLibrary(JniUtils.java:49)
(raylet)        at io.ray.runtime.util.JniUtils.loadLibrary(JniUtils.java:25)
(raylet)        at io.ray.streaming.runtime.util.EnvUtil.loadNativeLibraries(EnvUtil.java:33)
(raylet)        at io.ray.streaming.runtime.worker.JobWorker.<clinit>(JobWorker.java:48)
(raylet)        ... 15 more
(pid=174960) 2022-04-02 07:00:53,095 ERROR JobClientImpl [main]: Failed to submit job: HybridStreamTest.
(pid=174960) java.lang.RuntimeException: submitting job failed
(pid=174960)    at io.ray.streaming.runtime.client.JobClientImpl.submit(JobClientImpl.java:48) [raystreaming_dist.jar:?]

```

which means ray binary file util fails to extract libstreaming java so file

**Comment by ashione** [comment]
@BalaBalaYi Could you take a look this issue and make a solution that we can use to go through all of X-lang tests.
